apiVersion: v1
kind: Service
metadata:
  name: demo1
  labels:
    app: nginx-app
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - nodePort: 31000
      port: 8084
      targetPort: 8084
